//
//  RecipeDetailsInterfaces.swift
//  HelloFresh
//
//  Created by Danijel Kecman on 9/17/17.
//  Copyright (c) 2017 Danijel Kecman. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

enum RecipeDetailsNavigationOption {
}

protocol RecipeDetailsWireframeInterface: WireframeInterface {
    func navigate(to option: RecipeDetailsNavigationOption)
}

protocol RecipeDetailsViewInterface: ViewInterface {
}

protocol RecipeDetailsPresenterInterface: PresenterInterface {
    func getRecipeDto() -> RecipeDto
    func updateRecipe(with recipeDto: RecipeDto)
    func didChangeRatingFor(with rating: Int)
}

protocol RecipeDetailsInteractorInterface: InteractorInterface {
}
