//
//  RecipeDetailsInteractor.swift
//  HelloFresh
//
//  Created by Danijel Kecman on 9/17/17.
//  Copyright (c) 2017 Danijel Kecman. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class RecipeDetailsInteractor {
}

// MARK: - Extensions -

extension RecipeDetailsInteractor: RecipeDetailsInteractorInterface {
}
